/* eslint-disable */
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type PokemonFieldsFragment = { id: number, name: string, image: string | null, cryLatest: string | null, cryLegacy: string | null, spriteDefault: string | null, spriteShiny: string | null, spriteArtwork: string | null, spriteArtworkShiny: string | null, spriteShowdown: string | null, spriteShowdownShiny: string | null, types: Array<string>, abilities: Array<string>, height: number | null, weight: number | null, stats: Array<{ name: string, value: number }> } & { ' $fragmentName'?: 'PokemonFieldsFragment' };

export type PokemonByIdQueryVariables = Exact<{
  id: number;
}>;


export type PokemonByIdQuery = { pokemon: { ' $fragmentRefs'?: { 'PokemonFieldsFragment': PokemonFieldsFragment } } | null };

export type RandomPokemonQueryVariables = Exact<{ [key: string]: never; }>;


export type RandomPokemonQuery = { randomPokemon: { ' $fragmentRefs'?: { 'PokemonFieldsFragment': PokemonFieldsFragment } } };

export const PokemonFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PokemonFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Pokemon"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"image"}},{"kind":"Field","name":{"kind":"Name","value":"cryLatest"}},{"kind":"Field","name":{"kind":"Name","value":"cryLegacy"}},{"kind":"Field","name":{"kind":"Name","value":"spriteDefault"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShiny"}},{"kind":"Field","name":{"kind":"Name","value":"spriteArtwork"}},{"kind":"Field","name":{"kind":"Name","value":"spriteArtworkShiny"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShowdown"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShowdownShiny"}},{"kind":"Field","name":{"kind":"Name","value":"types"}},{"kind":"Field","name":{"kind":"Name","value":"abilities"}},{"kind":"Field","name":{"kind":"Name","value":"height"}},{"kind":"Field","name":{"kind":"Name","value":"weight"}},{"kind":"Field","name":{"kind":"Name","value":"stats"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"value"}}]}}]}}]} as unknown as DocumentNode<PokemonFieldsFragment, unknown>;
export const PokemonByIdDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PokemonById"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"pokemon"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"PokemonFields"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PokemonFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Pokemon"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"image"}},{"kind":"Field","name":{"kind":"Name","value":"cryLatest"}},{"kind":"Field","name":{"kind":"Name","value":"cryLegacy"}},{"kind":"Field","name":{"kind":"Name","value":"spriteDefault"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShiny"}},{"kind":"Field","name":{"kind":"Name","value":"spriteArtwork"}},{"kind":"Field","name":{"kind":"Name","value":"spriteArtworkShiny"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShowdown"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShowdownShiny"}},{"kind":"Field","name":{"kind":"Name","value":"types"}},{"kind":"Field","name":{"kind":"Name","value":"abilities"}},{"kind":"Field","name":{"kind":"Name","value":"height"}},{"kind":"Field","name":{"kind":"Name","value":"weight"}},{"kind":"Field","name":{"kind":"Name","value":"stats"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"value"}}]}}]}}]} as unknown as DocumentNode<PokemonByIdQuery, PokemonByIdQueryVariables>;
export const RandomPokemonDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"RandomPokemon"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"randomPokemon"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"PokemonFields"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PokemonFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Pokemon"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"image"}},{"kind":"Field","name":{"kind":"Name","value":"cryLatest"}},{"kind":"Field","name":{"kind":"Name","value":"cryLegacy"}},{"kind":"Field","name":{"kind":"Name","value":"spriteDefault"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShiny"}},{"kind":"Field","name":{"kind":"Name","value":"spriteArtwork"}},{"kind":"Field","name":{"kind":"Name","value":"spriteArtworkShiny"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShowdown"}},{"kind":"Field","name":{"kind":"Name","value":"spriteShowdownShiny"}},{"kind":"Field","name":{"kind":"Name","value":"types"}},{"kind":"Field","name":{"kind":"Name","value":"abilities"}},{"kind":"Field","name":{"kind":"Name","value":"height"}},{"kind":"Field","name":{"kind":"Name","value":"weight"}},{"kind":"Field","name":{"kind":"Name","value":"stats"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"value"}}]}}]}}]} as unknown as DocumentNode<RandomPokemonQuery, RandomPokemonQueryVariables>;